# @author Simon de Hartog <simon@fs2a.pro>
# @copyright Fs2a Ltd. (c) 2019
# vim:set ts=4 sw=4 noexpandtab:

FROM scratch

#ADD make.conf /etc/portage/make.conf
#RUN echo 'EMERGE_DEFAULT_OPTS="--usepkgonly"' >> /etc/portage/make.conf
